config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "fabrics#index"

  resources :fabrics

  get "signup" => "users#new"
  get "signin" => "sessions#new"

  resource :session
end

app/models/fabric.rb
class Fabric < ActiveRecord::Base
  def name
    "#{color} #{pattern} #{fabric_type}".titleize
  end

  def treated?
    !!treated
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, format: /\A\S+@\S+\z/, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8, allow_blank: true }

  def self.authenticate(email_or_username, password)
    user = User.find_by(email: email_or_username) || User.find_by(username: email_or_username)
    user &&user.authenticate(password)
  end

  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_flash_types(:danger)

  private

  def require_signin
    unless current_user
      redirect_to new_session_url, alert: "Please sign in first!"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/fabrics_controller.rb
class FabricsController < ApplicationController
  def index
    @fabrics = Fabric.all
  end

  def show
    @fabric = Fabric.find(params[:id])
  end

  def edit
    @fabric = Fabric.find(params[:id])
  end

  def update
    @fabric = Fabric.find(params[:id])
    @fabric.update(fabric_params)
    redirect_to @fabric
  end

  def new
    @fabric = Fabric.new
  end

  def create
    @fabric = Fabric.new(fabric_params)
    @fabric.save!
    redirect_to @fabric
  end

  def destroy
    @fabric = Fabric.find(params[:id])
    @fabric.destroy
    redirect_to fabrics_path
  end

  private

  def fabric_params
    params.require(:fabric).permit(:fabric_type, :color, :pattern, :length, :width, :price, :description, :offered_on, :image_file_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.name}!"
      redirect_to user
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You are now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Account successfully deleted!"
  end

private

  def user_params
    params.require(:user).
      permit(:name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/fabrics_helper.rb
module FabricsHelper
  def treated_show_method(fabric)
    if fabric.treated?
      fabric.treatment_method.capitalize
    else
      "Not treated"
    end
  end

  def image_for(fabric)
    if fabric.image_file_name.blank?
      image_tag("placeholder.png")
    else
      image_tag(fabric.image_file_name, size: "200x200")
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def profile_image_for(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.name)
  end
end

app/views/fabrics/_form.html.haml
= form_for(@fabric) do |f|
  %p
    = f.label :fabric_type
    = f.text_field :fabric_type, autofocus: true

  %p
    = f.label :color
    = f.text_field :color

  %p
    = f.label :pattern
    = f.text_field :pattern

  %p
    = f.label :description
    %br
    = f.text_area :description, cols: 40, rows: 7

  %p
    = f.label :length
    = f.number_field :length

  %p
    = f.label :width
    = f.number_field :width

  %p
    = f.label :price
    = f.number_field :price, step: 0.01

  %p
    = f.label :offered_on
    = f.date_select :offered_on, order: [:month, :day, :year]

  %p
    = f.label :image_file_name
    %br
    = f.text_field :image_file_name

  = f.submit
  |
  = link_to("Cancel", fabrics_path)

app/views/fabrics/edit.html.haml
%h3
  = "Editing #{@fabric.name}"

= render "form"

app/views/fabrics/index.html.haml
%h1= pluralize(@fabrics.count, "Fabrics")

= link_to("Add new fabric", new_fabric_path)

- @fabrics.each do |fabric|
  %article.fabric
    %h2
      = link_to(fabric.name, fabric)
      %br
      = image_for(fabric)
    %p
      %header
        Description:
      = truncate(fabric.description, length: 25, separator: " ")
    %p
      %header
        Treated:
        = treated_show_method(fabric)
    %table
      %tr
        %th Width:
        %td= "#{fabric.width} inches wide"
      %tr
        %th Length
        %td= "#{fabric.length} inches long"
      %tr
        %th Price
        %td= number_to_currency(fabric.price)
      %tr
        %th Time on site:
        %td= time_ago_in_words(fabric.offered_on)

app/views/fabrics/new.html.haml
%h3
  = "Create fabric"

= render "form"

app/views/fabrics/show.html.haml
%article
  %header
    %h2
      = @fabric.name
  %p
    %header
      Description:
    = @fabric.description
  %p
    %header
      Treated:
      = treated_show_method(@fabric)
  %table
    %tr
      %th Width:
      %td= "#{@fabric.width} inches wide"
    %tr
      %th Length
      %td= "#{@fabric.length} inches long"
    %tr
      %th Price
      %td= number_to_currency(@fabric.price)
    %tr
      %th Time on site:
      %td= time_ago_in_words(@fabric.offered_on)

  %h3
    Image
  = image_for(@fabric)
%nav
  = link_to("See All fabrics", root_path)
  |
  = link_to("Edit", edit_fabric_path)
  |
  = link_to("Delete", fabric_path(@fabric), method: :delete, data: { confirm: 'Are you sure?' })

app/views/layouts/_flashes.html.haml
- flash.each do |key, value|
  = content_tag(:p, value, :class => "flash #{key}")

app/views/layouts/_footer.html.haml
%footer#page-footer
  %p
    Copyright &copy; 2015

app/views/layouts/_header.html.haml
%header#page-header
  #masthead
    %h1
      = Stash
    %nav
      %p
        - if current_user
          = link_to current_user.name, current_user, class: "button"
          = link_to "Account Settings", edit_user_path(current_user), class: "button"
          = link_to "Sign Out", session_path, method: :delete, class: "button"
        - else
          = link_to "Sign Up", signup_path, class: "button"
          = link_to "Sign In", signin_path, class: "button"

app/views/layouts/_sidebar.html.haml
%aside#sidebar
  %nav
    %ul
      %li
        = link_to 'All Fabrics', fabrics_path
      %li
        = link_to 'Add New Fabric', new_fabric_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Stash
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render "layouts/header"

    = render "layouts/flashes"

    = render "layouts/sidebar"

    = yield

    = render "layouts/footer"

app/views/shared/_errors.html.haml
- if object.errors.any?
  %section#errors
    %header
      %h2
        Oops! The #{object.class.name.humanize.downcase} could not be saved.
      %h3
        Please correct the following #{pluralize(object.errors.count, "error")}:
    %ul
      - object.errors.full_messages.each do |message|
        %li= message

app/views/users/_form.html.haml
= form_for(@user) do |f|
  = render "shared/errors", object: @user
  %fieldset
    %ol
      %li.required
        = f.label :name
        = f.text_field :name, size: 40, autofocus: true
      %li.required
        = f.label :username
        = f.text_field :username, size: 40
      %li.required
        = f.label :email
        = f.email_field :email, size: 40
      %li.required
        = f.label :password
        = f.password_field :password, size: 40
      %li.required
        = f.label :password_confirmation, "Confirm Password"
        = f.password_field :password_confirmation, size: 40
    %p
      - if @user.new_record?
        = f.submit "Create Account"
      - else
        = f.submit "Update Account"

app/views/users/edit.html.haml
%header#content-header
  %h1 Edit Account
= render 'form'

app/views/users/index.html.haml
%header#content-header
  %h1
    = pluralize(@users.size, "User")

%ul#users
  - @users.each do |user|
    %li= link_to user.name, user

app/views/users/new.html.haml
%header#content-header
  %h1 Sign Up

= render "form"

app/views/users/show.html.haml
%article#user
  %header
    = profile_image_for(@user)

    %h1= @user.name
    %h2= @user.username
    %h2= mail_to(@user.email)
    %h3
      Member since
      %p=@user.created_at.strftime("%B %Y")

  %footer
    %nav
      = link_to "Edit Account", edit_user_path(@user), class: "button"
      = link_to "Delete Account", @user,
          method: :delete,
          data: { confirm: "Are you sure?" },
          class:"button"